#!groovy

properties([disableConcurrentBuilds()])

pipeline {
    environment {
        git_repo = 'git@github.com:falkonz/DevOps_online_Kharkiv_2020Q42021Q1.git'
        git_dir = 'm8/task8.1/app'
        registry = "falkonz/finalproject"
        credId = 'dockerHub'
    }
    agent {
        label 'master'
    }
    triggers { pollSCM('H/2 * * * *') }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage('Clone') {
            steps {
                git git_repo
            }
        }
        stage("Build") {
            steps {
                echo " ============== Building =================="
                dir (git_dir) {
                    sh '''
                    docker build -t $registry:$BUILD_NUMBER .
                    '''
                }
            }
        }
        stage("Test") {
            steps {
                echo " ============== Testing =================="
                    sh '''
                    docker run -d -p 80:80 --name falkonz-finalproject-$BUILD_NUMBER -t $registry:$BUILD_NUMBER
                    curl --head http://0.0.0.0:80
                    '''
            }
        }
        stage("Deploy") {
            steps {
                echo " ============== Deploy in progress =================="
                withCredentials([usernamePassword(credentialsId: credId, usernameVariable: 'HUB_USER', passwordVariable: 'HUB_TOKEN')]) {
                    sh '''
                    echo "${HUB_TOKEN} | docker login -u ${HUB_USER} --password-stdin"
                    docker push $registry:$BUILD_NUMBER
                    docker rmi $registry:$BUILD_NUMBER
                    '''
                }
           }
       }
   }
}