#!groovy

properties([disableConcurrentBuilds()])

pipeline {
    environment {
        git_repo = 'git@github.com:falkonz/DevOps_online_Kharkiv_2020Q42021Q1.git'
        git_dir = 'm8/task8.1/app'
        registry = "falkonz/finalproject"
        credId = 'dockerHub'
    }
    agent { 
        label 'master'
    }
    triggers { pollSCM('H/2 * * * *') }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage('Git Clone') {
           steps {
                git git_repo
            }
        }
        stage("dockerhub login") {
            steps {
                echo " ============== docker login =================="
                withCredentials([usernamePassword(credentialsId: credId, usernameVariable: 'HUB_USER', passwordVariable: 'HUB_TOKEN')]) {
                    sh '''
                         echo "${HUB_TOKEN} | docker login -u ${HUB_USER} --password-stdin"
                    '''
                }
            }
        }
        stage("create docker image") {
            steps {
                echo " ============== start building image =================="
                dir (git_dir) {
            	sh '''
                    docker build -t $registry:$BUILD_NUMBER . 
                    '''
                }
            }
        }
        stage("docker push") {
            steps {
                echo " ============== start pushing image =================="
                    sh '''
                    docker push $registry:$BUILD_NUMBER
                    '''
            }
        }
        stage('Remove local docker image') {
            steps{
                echo " ============== start remove local image =================="
                    sh '''
                    docker rmi $registry:$BUILD_NUMBER
                     '''
            }
        }
    }
}