DOMAIN="test"

servers=[
  {
    :hostname => "vm3." + DOMAIN,
    :group => "/vm.group." + DOMAIN,
    :ram => 1024,
    :cpu => 1
  },

  {
    :hostname => "vm4." + DOMAIN,
    :group => "/vm.group." + DOMAIN,
    :ram => 512,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: true

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            
            node.vm.box = "vm1_sokolov"
        
            node.vm.usable_port_range = (2200..2250)
            node.vm.hostname = machine[:hostname]
            node.vm.network "public_network", bridge: "wmxd3d76c23a2168"
            node.ssh.keys_only = false
            node.ssh.username = "---||---"
            node.ssh.password = "---||---"
            node.vm.provider "virtualbox" do |vb|
                vb.name = machine[:hostname]
                vb.customize ["modifyvm", machine[:hostname], "--groups", machine[:group]]
                vb.memory = machine[:ram]
                vb.cpus = machine[:cpu]
            end
        end
    end

  config.vm.provision "nginx", type: "shell", inline: "echo Installing Nginx; apt-get install -y nginx"
  config.vm.provision "mysql", type: "shell", inline: "echo Installing MySQL; apt-get install -y mysql-server"
  config.vm.provision "php", type: "shell", inline: "echo Installing PHP; apt-get install -y php-fpm php-mysql"

end